### ISSUE TITLE
graph_simplification error

### ISSUE THREAD

**Issue by pbaCamille** [cguyomar/MinYS#4]
Hello,
I'm following the steps described in Genome assembly gap-filling using MindTheGap. I'm trying to simplfiy the graph I obtained using graph-simplification.py script. But it stops at the Merging redundancies step with this message
```
Merging redundancies
Traceback (most recent call last):
  File "/CONDAS/users/tc/minys/bin/graph_simplification.py", line 35, in <module>   
    g.merge_all_gapfillings(opts.l)
  File "/CONDAS/users/tc/minys/share/minys-1.1-3/graph_simplification/genome_graph/genome_graph.py", line 362, in merge_all_gapfillings
    self.merge_redundant_gapfillings(-node,l)
  File "/CONDAS/users/tc/minys/share/minys-1.1-3/graph_simplification/genome_graph/genome_graph.py", line 290, in merge_redundant_gapfillings
    neighbors_sequences = [self.get_node_seq(node) for node in neighbors]
  File "/CONDAS/users/tc/minys/share/minys-1.1-3/graph_simplification/genome_graph/genome_graph.py", line 290, in <listcomp>
    neighbors_sequences = [self.get_node_seq(node) for node in neighbors]
  File "/CONDAS/users/tc/minys/share/minys-1.1-3/graph_simplification/genome_graph/genome_graph.py", line 108, in get_node_seq
    nodeSeq = reverse_complement(self.nodes[-nodeId].nodeSeq.strip())
  File "/CONDAS/users/tc/minys/share/minys-1.1-3/graph_simplification/genome_graph/utils.py", line 10, in reverse_complement
    return ''.join([complement[base] for base in dna[::-1]])
  File "/CONDAS/users/tc/minys/share/minys-1.1-3/graph_simplification/genome_graph/utils.py", line 10, in <listcomp>
    return ''.join([complement[base] for base in dna[::-1]])
KeyError: 'N'
```
I supposed it is linked to some 'N' in my original data. Do I have to remove them ? It is unclear for me.
Thank you in advance for your answer.

**Comment by cguyomar** [comment]
Hi Camille,
Sorry, I just saw your issue. It was a quick fix so if it's still of interest for you you can give it a try with the latest git commit.
Sorry for the delay ;)
Cervin
